[package]
name = "qr_forge_web"
version = "0.1.0"
description = "WebAssembly bindings and browser application for qr_forge"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude = [
    "node_modules/**",
    "pkg/**",
    "playwright-report/**",
    "static/pkg/**",
    "test-results/**",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
qr_forge_core = { version = "0.1.0", path = "../qr_forge_core" }
wasm-bindgen.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
